### ISSUE TITLE
Magnet link parsing

### ISSUE THREAD

**Issue by pR0Ps** [torrage/Torrage#4]
Would you consider accepting a pull request for a feature automatically parses magnet links, pulls out the info hash, and redirects to the proper torrent file?

For example, if a user goes to: `http://torrage.com/magnet?l=magnet:?xt=urn:btih:640fe84c613c17f663551d218689a64e8aebeabe&dn=slackware-12.2-dvd-iso&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80` it would automatically redirect them to `http://torrage.com/torrent/640FE84C613C17F663551D218689A64E8AEBEABE.torrent`

I've made a web application that does this already (https://github.com/pR0Ps/mag2tor), but I think it would be nicer if it was directly integrated with the service.

Note that I'm not proposing storing or searching by filename, just another way of accessing the file via the info_hash.

**Comment by jonasbits** [comment]
hmm

**Comment by novaking** [comment]
Issue is magnet links may contain HEX values instead of SHA1, but to be honest why would someone paste an entire magnet string when they can just put in the hash.torrent?
