### ISSUE TITLE
Torrent storage

### ISSUE THREAD

**Issue by LordMike** [torrage/Torrage#7]
Do you have any comments on torrent storage? It seems to me that every torrent is stored under a URI which can be rewritten in many ways to either directly access the underlying filesystem, or use a database/storage of some sort.

Do you have any comments on what works for you, how many .torrent files there are, and what issues there are? I could imagine that with an rsync sync, that working on ~10 million files might be an issue.

For the record, I currently have 20 million .torrent files.

**Comment by novaking** [comment]
You are welcome to store them anyway you wish, but as you would probably know ~20mil gzip'd torrents is about 450GB as having that in a database probably would be fun. the current method used on torrage appears to work fine (you could go one further and break it down another 2 chars to make each folder contain less torrent files)

**Comment by LordMike** [comment]
I'm working right now with 2 levels - [byte0]/[byte1]/[hash].torrent - which gives around 300 torrents pr. directory. Finding a single torrent file is fast, insertion and listing not so much. I've been working with both BTRFS and EXT3/4. I even tried having 16 disks attached, each representing the first nibble of the hash (0-F) but that didn't help either.

I'm currently experimenting with 2 levels and then in a zip file - [byte0]/[byte1].zip - and in PHP reading out a single entry from the zip. It seems to work ok, and I'll have only 65.536 files keeping filesystems happy.

And you're spot on with the size. I have them in 1040 zip files of 20.000 torrents each, totalling 467 GiB. Zipping aproximately halves it in size.

**Comment by novaking** [comment]
Listing will always be slow with the shear amount of files. You could possibly speed it up by using an index file (reference /sync/ folder maybe?), but i'm confused by why it is slow to insert?

What I am unsure of why you store them in a zip file? the torrent files are already themselves compressed, so all you are doing is compressing a compressed file, which usually makes it larger.

as for FS, if you have access to multiple drives, maybe a NAS setup with ZFS using SSDs (or memory if you got a lot spare) as read/write cache, might be a better setup.

**Comment by LordMike** [comment]
Right now I'm experimenting with zip files as they're pretty cheap computationally, and they can reduce the # of files by 300x thereby speeding up all operations on the filesystem.

Inserts are slow, On the filesystems I tested, I found that I had a very high insert speed (hundres/thousdands pr. second) in the beginning, which crawled to 40/60 torrents pr. second when I was just under halfway. Previous experience tells me that all filesystems are bad at handling many files - not matter the size, layout, purpose or similar.

But the original question in this issue was, which storage system does torrage.com use?

**Comment by LordMike** [comment]
Small addendum:
The advantage of making 65536 small zip files is that I get that many small filesystems each handling a 1/65536th piece of the workload. You mentioning them being gzipped made me realize I didn't take the actual use case into consideration, as they're actually not pre-compressed as the webserver would deliver them. (They're actually uncompressed).

A similar storage would be tar-files in which each file is gzipped - ripe for serving.

**Comment by novaking** [comment]
Well, what you see in the codebase should tell you what torrage uses... as for physical hardware, it's a single 2TB Sata II HDD

/[1-2]/[3-4]/[5-40].torrent in gzip format

as seen here:

https://github.com/torrage/Torrage/blob/master/inc/settings.inc.php#L215

The files are indeed gzip'd on upload so when serving the data, you just have to set the appropriate Content-Encoding and no extra load to gzip the data needs to be done as the files are already gzip'd

As torrage is purely a storage, and not aim'd for searching and the sorts, the current layout works fine for it. If you are wishing to expand to be able to search files, it would be better to create an index file of available hashes and search based off that index instead of searching the actual filesystem.

If speed is also a concern, look into RAID configurations to utilize better I/O.

**Comment by LordMike** [comment]
Thanks :)
I couldn't find that part in code. 

Also thanks for the chat ;).
